language: ruby
cache: bundler
rvm:
  - 2.3.0
  - 2.3.1
sudo: false
before_install:
  - gem install bundler -v 1.14.3
install:
  - bundle install
  - npm install -g elm@0.18
  - elm-package install --yes
